name: Team awesome's approval workflow
on: [pull_request_review, push]
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Add label on approval
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
